// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: carts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateCart = `-- name: GetOrCreateCart :one
INSERT INTO carts (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) GetOrCreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getOrCreateCart, userID)
	var c Cart
	err := row.Scan(&c.ID, &c.UserID, &c.CreatedAt, &c.UpdatedAt)
	return c, err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at FROM carts WHERE user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var c Cart
	err := row.Scan(&c.ID, &c.UserID, &c.CreatedAt, &c.UpdatedAt)
	return c, err
}

// GetCartItemsRow joins cart_items with product details.
type GetCartItemsRow struct {
	ID              uuid.UUID      `json:"id"`
	CartID          uuid.UUID      `json:"cart_id"`
	ProductID       uuid.UUID      `json:"product_id"`
	Quantity        int32          `json:"quantity"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ProductName     string         `json:"product_name"`
	ProductPrice    pgtype.Numeric `json:"product_price"`
	ProductImageUrl pgtype.Text    `json:"product_image_url"`
	ProductStock    int32          `json:"product_stock"`
}

const getCartItems = `-- name: GetCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at,
       p.name AS product_name, p.price AS product_price,
       p.image_url AS product_image_url, p.stock_quantity AS product_stock
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1 ORDER BY ci.created_at ASC
`

func (q *Queries) GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID, &i.CartID, &i.ProductID, &i.Quantity,
			&i.CreatedAt, &i.UpdatedAt,
			&i.ProductName, &i.ProductPrice, &i.ProductImageUrl, &i.ProductStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, product_id) DO UPDATE SET quantity = $3, updated_at = NOW()
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpsertCartItemParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(&i.ID, &i.CartID, &i.ProductID, &i.Quantity, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items SET quantity = $2, updated_at = NOW()
WHERE id = $1 AND cart_id = $3
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
	CartID   uuid.UUID `json:"cart_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity, arg.CartID)
	var i CartItem
	err := row.Scan(&i.ID, &i.CartID, &i.ProductID, &i.Quantity, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = $1 AND cart_id = $2
`

type DeleteCartItemParams struct {
	ID     uuid.UUID `json:"id"`
	CartID uuid.UUID `json:"cart_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.CartID)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}
