// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID          `json:"id"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	PhoneNumber  string             `json:"phone_number"`
	EmailAddress string             `json:"email_address"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type EmailOtp struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OtpHash      string    `json:"otp_hash"`
	ExpiresAt    time.Time `json:"expires_at"`
	IsUsed       bool      `json:"is_used"`
	AttemptCount int32     `json:"attempt_count"`
	CreatedAt    time.Time `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID            uuid.UUID          `json:"id"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	ImageUrl      pgtype.Text        `json:"image_url"`
	StockQuantity int32              `json:"stock_quantity"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Cart struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartItem struct {
	ID        uuid.UUID `json:"id"`
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	DeliveryAddress string         `json:"delivery_address"`
	DeliveryDate    time.Time      `json:"delivery_date"`
	Notes           pgtype.Text    `json:"notes"`
	PaymentMethod   string         `json:"payment_method"`
	Status          string         `json:"status"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type OrderItem struct {
	ID         uuid.UUID      `json:"id"`
	OrderID    uuid.UUID      `json:"order_id"`
	ProductID  uuid.UUID      `json:"product_id"`
	Quantity   int32          `json:"quantity"`
	UnitPrice  pgtype.Numeric `json:"unit_price"`
	TotalPrice pgtype.Numeric `json:"total_price"`
	CreatedAt  time.Time      `json:"created_at"`
}
