// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// GetProductByIDRow is returned by GetProductByID, joining category fields.
type GetProductByIDRow struct {
	Product
	CategoryName pgtype.Text `json:"category_name"`
	CategorySlug pgtype.Text `json:"category_slug"`
}

// ListProductsRow is returned by ListProducts, joining category fields.
type ListProductsRow struct {
	Product
	CategoryName pgtype.Text `json:"category_name"`
	CategorySlug pgtype.Text `json:"category_slug"`
}

type ListProductsParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	SortBy     pgtype.Text `json:"sort_by"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.category_id, p.name, p.description, p.price, p.image_url,
       p.stock_quantity, p.is_active, p.created_at, p.updated_at, p.deleted_at,
       c.name AS category_name, c.slug AS category_slug
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.deleted_at IS NULL
  AND p.is_active = TRUE
  AND ($1::uuid IS NULL OR p.category_id = $1)
ORDER BY
  CASE WHEN $2::text = 'price_asc'  THEN p.price END ASC,
  CASE WHEN $2::text = 'price_desc' THEN p.price END DESC,
  p.created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID, arg.SortBy, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var products []ListProductsRow
	for rows.Next() {
		var p ListProductsRow
		if err := rows.Scan(
			&p.ID, &p.CategoryID, &p.Name, &p.Description, &p.Price,
			&p.ImageUrl, &p.StockQuantity, &p.IsActive, &p.CreatedAt,
			&p.UpdatedAt, &p.DeletedAt, &p.CategoryName, &p.CategorySlug,
		); err != nil {
			return nil, err
		}
		products = append(products, p)
	}
	return products, rows.Err()
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.category_id, p.name, p.description, p.price, p.image_url,
       p.stock_quantity, p.is_active, p.created_at, p.updated_at, p.deleted_at,
       c.name AS category_name, c.slug AS category_slug
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var p GetProductByIDRow
	err := row.Scan(
		&p.ID, &p.CategoryID, &p.Name, &p.Description, &p.Price,
		&p.ImageUrl, &p.StockQuantity, &p.IsActive, &p.CreatedAt,
		&p.UpdatedAt, &p.DeletedAt, &p.CategoryName, &p.CategorySlug,
	)
	return p, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE deleted_at IS NULL AND is_active = TRUE
AND ($1::uuid IS NULL OR category_id = $1)
`

func (q *Queries) CountProducts(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deductProductStock = `-- name: DeductProductStock :exec
UPDATE products SET stock_quantity = stock_quantity - $2, updated_at = NOW()
WHERE id = $1 AND stock_quantity >= $2
`

type DeductProductStockParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) DeductProductStock(ctx context.Context, arg DeductProductStockParams) error {
	_, err := q.db.Exec(ctx, deductProductStock, arg.ID, arg.Quantity)
	return err
}

const getProductsForOrder = `-- name: GetProductsForOrder :many
SELECT id, name, price, stock_quantity
FROM products WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL AND is_active = TRUE
`

type GetProductsForOrderRow struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
}

func (q *Queries) GetProductsForOrder(ctx context.Context, ids []uuid.UUID) ([]GetProductsForOrderRow, error) {
	rows, err := q.db.Query(ctx, getProductsForOrder, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var products []GetProductsForOrderRow
	for rows.Next() {
		var p GetProductsForOrderRow
		if err := rows.Scan(&p.ID, &p.Name, &p.Price, &p.StockQuantity); err != nil {
			return nil, err
		}
		products = append(products, p)
	}
	return products, rows.Err()
}

type CreateProductParams struct {
	CategoryID    pgtype.UUID    `json:"category_id"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	Price         pgtype.Numeric `json:"price"`
	ImageUrl      pgtype.Text    `json:"image_url"`
	StockQuantity int32          `json:"stock_quantity"`
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (category_id, name, description, price, image_url, stock_quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, category_id, name, description, price, image_url, stock_quantity, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID, arg.Name, arg.Description, arg.Price, arg.ImageUrl, arg.StockQuantity,
	)
	var p Product
	err := row.Scan(
		&p.ID, &p.CategoryID, &p.Name, &p.Description, &p.Price,
		&p.ImageUrl, &p.StockQuantity, &p.IsActive, &p.CreatedAt, &p.UpdatedAt, &p.DeletedAt,
	)
	return p, err
}
