// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, phone_number, email_address)
VALUES ($1, $2, $3, $4)
RETURNING id, first_name, last_name, phone_number, email_address, is_verified, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PhoneNumber  string `json:"phone_number"`
	EmailAddress string `json:"email_address"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName, arg.LastName, arg.PhoneNumber, arg.EmailAddress,
	)
	var u User
	err := row.Scan(
		&u.ID, &u.FirstName, &u.LastName, &u.PhoneNumber,
		&u.EmailAddress, &u.IsVerified, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	return u, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, phone_number, email_address, is_verified, created_at, updated_at, deleted_at
FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var u User
	err := row.Scan(
		&u.ID, &u.FirstName, &u.LastName, &u.PhoneNumber,
		&u.EmailAddress, &u.IsVerified, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	return u, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, phone_number, email_address, is_verified, created_at, updated_at, deleted_at
FROM users WHERE email_address = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailAddress)
	var u User
	err := row.Scan(
		&u.ID, &u.FirstName, &u.LastName, &u.PhoneNumber,
		&u.EmailAddress, &u.IsVerified, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	return u, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, first_name, last_name, phone_number, email_address, is_verified, created_at, updated_at, deleted_at
FROM users WHERE phone_number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var u User
	err := row.Scan(
		&u.ID, &u.FirstName, &u.LastName, &u.PhoneNumber,
		&u.EmailAddress, &u.IsVerified, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	return u, err
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE users SET is_verified = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, phone_number, email_address, is_verified, created_at, updated_at, deleted_at
`

func (q *Queries) MarkUserVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var u User
	err := row.Scan(
		&u.ID, &u.FirstName, &u.LastName, &u.PhoneNumber,
		&u.EmailAddress, &u.IsVerified, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	return u, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}
